name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "20749119-aca1fb7e-cc0d-40a7-935b-152ffb47a9cb"
      - name: Install Latency Lingo
        run: curl -L https://github.com/AnthonyBobsin/latency-lingo-cli/releases/latest/download/latency-lingo-cli_Linux_x86_64.tar.gz | tar -xz
      - name: Publish to Latency Lingo
        run: ./latency-lingo-cli publish --file result.jtl --api-key $LATENCY_LINGO_API_KEY --label 'Checkout Flow Automated Test Plan'
        env:
          LATENCY_LINGO_API_KEY: ${{ secrets.LATENCY_LINGO_API_KEY }}
